// The farm families of Inaba, west along the road from Kumoi.

import { asleep, chase, home, spot, wander, work, type VillagerSpec } from './types'

export const FARM: VillagerSpec[] = [
  {
    id: 'gonbei',
    name: 'Gonbei',
    title: 'rice farmer',
    home: 'door:gonbei',
    color: '#3a5a9a',
    speed: 30,
    look: { hair: 'topknot', hat: 'kasa', robe: '#3c5788', robeShade: '#2b3f66', sash: '#c9b58a', legs: '#3c5788', collar: '#e8e0cc' },
    schedule: [
      asleep(),
      { at: '05:20', label: 'stretching', doing: spot('gonbeiStep'), say: 'Another day, another thousand seedlings. Ow, my back.' },
      { at: '05:40', label: 'planting rice', doing: work('paddies', 'plant') },
      home('11:30', 'lunch at home'),
      { at: '12:30', label: 'planting rice', doing: work('paddies', 'plant') },
      { at: '17:30', label: 'drinking tea in town (allegedly)', doing: spot('teaBench1', 'sit') },
      home('19:40', 'home for dinner'),
      asleep('21:30'),
    ],
    talk: [
      'Gonbei sows the seeds, the crows dig them up. They made a proverb about me. Nobody asked me.',
      'A turtle in my paddy is good luck. A crow in my paddy is a crow.',
      'They say turtles live ten thousand years. Must be nice. My knees are forty and already retired.',
      'Ohana plants faster than me. Don’t tell her I said so. She knows.',
      'Town folk buy my rice, then complain it’s muddy. It’s RICE. It grows in MUD.',
    ],
    turtle: ['Oh! A turtle! Lucky day!', 'A turtle at the farm? That’s ten thousand years of luck. I’ll take some.'],
    shell: ['Huh. Was that rock always there?', 'Good rock. Solid rock.'],
    night: ['It’s late, little turtle. Even the crows are asleep. Well. Pretending.'],
    barks: {
      plant: ['One seedling… two seedlings…', 'Ow. My back.', 'Shoo! SHOO! Filthy crows!', 'Rows straight as an arrow. Mostly.', 'Mud between my toes. The farmer’s perfume.'],
      sit: ['One cup. Then home. …Two cups.', 'Ahh. The crows can’t follow me into town.'],
    },
  },
  {
    id: 'ohana',
    name: 'Ohana',
    title: 'Gonbei’s wife',
    home: 'door:gonbei',
    color: '#c96a3a',
    speed: 32,
    look: { hair: 'bun', hat: 'tenugui', robe: '#b8613a', robeShade: '#8e4528', sash: '#2f3f73', legs: '#3d3449', collar: '#f1e6cc' },
    schedule: [
      asleep(),
      { at: '05:35', label: 'feeding the hens', doing: { kind: 'area', area: 'chickenYard', pose: 'feed', style: 'wander' } },
      { at: '06:50', label: 'hanging laundry', doing: spot('laundryFarm') },
      { at: '07:20', label: 'planting rice', doing: work('paddies', 'plant') },
      home('11:00', 'cooking lunch'),
      { at: '12:20', label: 'selling eggs in the square', doing: spot('vegStall', 'shop'), say: 'Eggs! Fresh eggs! Laid this morning by hens with opinions!' },
      { at: '14:30', label: 'planting rice', doing: work('paddies', 'plant') },
      { at: '17:00', label: 'calling the children', doing: spot('callKids', 'call'), say: 'TARO! KIKU! DINNER!', shout: true },
      home('17:30', 'cooking dinner'),
      asleep('21:00'),
    ],
    talk: [
      'Gonbei talks to the crows. The crows talk back. Neither one listens.',
      'Eggs, rice, laundry, two children and a dog. And now a turtle. Wipe your feet.',
      'The hens like you. They like anything slower than them.',
      'In town they pay twice what an egg is worth. I don’t tell them. That’s called business.',
    ],
    turtle: ['A turtle! Children, don’t— too late, they’ve seen it.'],
    shell: ['Who left a rock in my yard?'],
    barks: {
      feed: ['Here, chick-chick-chick!', 'Not you, rooster. Ladies first.', 'Nobunaga! Share!'],
      plant: ['Faster, Gonbei, the sun won’t wait.', 'Plant, step, plant, step…'],
      call: ['If I count to ten… ONE…', 'TARO! KIKU!'],
      shop: ['Eggs! Eggs from the country!', 'One egg, one copper. Two eggs, also one copper if you’re pretty.'],
    },
  },
  {
    id: 'taro',
    name: 'Taro',
    title: 'future ninja (self-declared)',
    home: 'door:gonbei',
    color: '#5f9a4a',
    speed: 44,
    look: { kid: true, hair: 'kidBoy', robe: '#5f8f5a', robeShade: '#456c42', sash: '#e0b13c', legs: '#f2c9a0' },
    schedule: [
      asleep(),
      { at: '06:30', label: 'chasing chickens', doing: chase('chickenYard') },
      { at: '08:00', label: 'ninja training in town', doing: wander('square', 'play') },
      { at: '10:30', label: 'chasing seagulls at the harbour', doing: wander('quay', 'play') },
      home('12:00', 'lunch'),
      { at: '13:00', label: 'playing on the west beach', doing: wander('beachWest', 'play') },
      { at: '15:00', label: 'hiding in the paddies', doing: wander('farmLane', 'play') },
      { at: '16:00', label: 'chasing chickens', doing: chase('chickenYard') },
      home('17:15', 'home for dinner'),
      asleep('20:30'),
    ],
    talk: [
      'I’m going to be a ninja. I already know how to be quiet. Watch. … …See?',
      'Kiku says turtles can’t be ninja. You’re a ninja, right? Blink twice.',
      'Hachi from town says real ninja come from Iga. Iga’s just over the mountains. I could walk there. After lunch.',
      'Pochi caught a chicken once. Then the chicken caught Pochi.',
    ],
    turtle: ['A TURTLE! Kiku! KIKU! A TURTLE!', 'Can I ride you? I’m small. Mostly.'],
    shell: ['It went into its house! Hello? Anybody home?'],
    barks: { play: ['Hyaa! Ninja leap!', 'Get the chicken!', 'You can’t see me, I’m in the shadows!', 'Shuriken! Shhhk!'] },
  },
  {
    id: 'kiku',
    name: 'Kiku',
    title: 'Taro’s little sister, the boss',
    home: 'door:gonbei',
    color: '#d0505a',
    speed: 40,
    look: { kid: true, hair: 'kidGirl', robe: '#d0505a', robeShade: '#a33a44', sash: '#f1e6cc', legs: '#f2c9a0' },
    schedule: [
      asleep(),
      { at: '06:40', label: 'chasing a hen called Nobunaga', doing: chase('chickenYard') },
      { at: '08:10', label: 'bossing Taro around in town', doing: wander('square', 'play') },
      { at: '10:40', label: 'looking at fish', doing: wander('docks', 'play') },
      home('12:00', 'lunch'),
      { at: '13:10', label: 'building sand castles', doing: wander('beachWest', 'play') },
      { at: '16:10', label: 'chasing Nobunaga the hen', doing: chase('chickenYard') },
      home('17:15', 'home for dinner'),
      asleep('20:00'),
    ],
    talk: [
      'My brother is not a ninja. He fell in the duck pond twice. Today.',
      'Turtles live ten thousand years. I’ll still be your friend when I’m a hundred.',
      'I named the bossy hen Nobunaga. She pecks everybody and nobody stops her.',
      'When I grow up I’m going to run the teahouse. And the manor. And Taro.',
    ],
    turtle: ['Hi turtle! Do you want to be my turtle?', 'Taro, look! No, MY turtle. I saw it first.'],
    shell: ['Knock knock! …Rude.'],
    barks: { play: ['Taro, you’re doing it wrong!', 'Come back, Nobunaga!', 'This castle is MINE. The sand one.'] },
  },
  {
    id: 'kiyo',
    name: 'Kiyo',
    title: 'farmer, sixty years and counting',
    home: 'door:kiyo',
    color: '#8a6a50',
    speed: 22,
    look: { hair: 'grayBun', hat: 'tenugui', robe: '#7a5a42', robeShade: '#5a412e', sash: '#3d3449', legs: '#3d3449', collar: '#c9c1b0' },
    schedule: [
      asleep(),
      { at: '04:30', label: 'weeding the fields', doing: work('fields', 'hoe') },
      { at: '06:30', label: 'selling vegetables in the square', doing: spot('vegStall2', 'shop'), say: 'Vegetables. Fresh. Don’t squeeze them.' },
      { at: '10:30', label: 'feeding Benkei the ox', doing: spot('oxGate', 'tend') },
      home('11:30', 'lunch'),
      { at: '13:00', label: 'gossiping at the teahouse', doing: spot('teaBench2', 'sit') },
      { at: '15:00', label: 'weeding the fields', doing: work('fields', 'hoe') },
      home('18:00'),
      asleep('20:00'),
    ],
    talk: [
      'Sixty years I’ve weeded this field. The weeds are winning on points.',
      'Those Iga folk glean my paddy edges at dusk. I leave the edges messy. Lazy farming. That’s all it is.',
      'I was going to make you into soup. Then I remembered I’m too tired to chase anything. Even you.',
      'That old hermit on the island courted me once. I said no. He’s been sulking on that island for fifty years.',
      'Town people. They pay for vegetables and then ask where vegetables come from. The GROUND, dear.',
    ],
    turtle: ['Hmph. A turtle. Faster than the last tax collector.'],
    shell: ['Don’t think I can’t see you, turtle. I’m old, not blind.'],
    barks: {
      hoe: ['Hmph.', 'Weeds. Always weeds.', 'My back says it’s going to rain. My back is a liar.'],
      sit: ['Oume, did you hear about the brewer’s nephew…', 'Tea’s weak today. Like the young people.'],
      tend: ['Eat, Benkei. You’re not getting any prettier.'],
      shop: ['Daikon. Eggplant. Don’t squeeze.', 'I said DON’T SQUEEZE.'],
    },
  },
  {
    id: 'yasaku',
    name: 'Yasaku',
    title: 'carter, hauls rice to town',
    home: 'door:yasaku',
    color: '#9a7a4a',
    speed: 26,
    look: { hair: 'short', hat: 'hachimaki', robe: '#8a7050', robeShade: '#6a5236', sash: '#3d3449', legs: '#f2c9a0', collar: '#c9b58a' },
    schedule: [
      asleep(),
      home('05:00', 'loading the cart'),
      {
        at: '06:00',
        label: 'hauling rice to the warehouses',
        doing: { kind: 'patrol', route: ['farmRoad', 'riceFront', 'warehouseFront', 'farmRoad'], pose: 'carry', stop: 'stand', wait: 6 },
      },
      { at: '12:00', label: 'lunch on the beach', doing: spot('beachWestSpot', 'sit') },
      {
        at: '13:00',
        label: 'hauling rice to the warehouses',
        doing: { kind: 'patrol', route: ['farmRoad', 'warehouseFront', 'riceFront', 'farmRoad'], pose: 'carry', stop: 'stand', wait: 6 },
      },
      { at: '18:00', label: 'at the tavern', doing: spot('tavernIn1', 'sit') },
      home('20:30'),
      asleep('21:30'),
    ],
    talk: [
      'Rice in, rice out. I carry the whole town’s wealth on my back and they pay me in rice. Which I carry.',
      'My cart has one wheel smaller than the other. I walk instead. It’s faster.',
      'The harbour master keeps asking for "a fast boat". I said: try a fast cart. He didn’t laugh.',
    ],
    turtle: ['A turtle! You carry your house. I carry everybody else’s rice. We’re basically colleagues.'],
    shell: ['If you were a rice bale, I’d carry you. You’re not. Sorry.'],
    barks: { carry: ['Hup!', 'Mind your toes!', 'Rice coming through!'], walk: ['Rice coming through!'], sit: ['Ahh. My shoulders.'] },
  },
]
