// The refugee camp on the common between Inaba and Kumoi. Iga province was burned by Oda Nobunaga last autumn
// (the Tenshō Iga War, 1581); the survivors who walked to the coast live in tents of rice sacking
// on the common by the west road. The village lets them stay. Mostly.

import { asleep, chase, home, patrol, spot, type VillagerSpec } from './types'

export const CAMP: VillagerSpec[] = [
  {
    id: 'sokyu',
    name: 'Sōkyū',
    title: 'refugee elder from Iga',
    home: 'door:tentA',
    color: '#8a8478',
    speed: 18,
    look: { hair: 'bald', robe: '#5a554a', robeShade: '#433f37', sash: '#2a2420', legs: '#5a554a', collar: '#8a8270', extras: ['beard'] },
    schedule: [
      asleep(),
      { at: '05:30', label: 'sitting by the fire', doing: spot('campFireW', 'sit'), say: 'Still here. All of us? …Most of us.' },
      home('11:40', 'sharing out the rice'),
      { at: '12:30', label: 'telling stories by the fire', doing: spot('campFireW', 'sit') },
      home('21:30', 'trying to sleep'),
    ],
    talk: [
      'We are from Iga. Were. Nobunaga came last autumn with forty thousand men. Iga had farmers. Now Iga has crows.',
      'They say all Iga folk are ninja. If I were a ninja, would I be sleeping in a tent made of rice sacks?',
      'The village lets us camp on the common. The houses are for people. The common is for us, the crows and the turtle.',
      'Every night I count who is left. It takes less time than it used to.',
      'The steward says Lord Nobunaga is in Kyoto. Good. Kyoto is far. Further would be better.',
      'Masa thinks I don’t know what he did last autumn. I know. I still share the fire. Someone has to stop the counting.',
    ],
    turtle: ['A turtle. In Iga we had a pond full of them. The soldiers ate them.', 'Don’t worry, little one. I won’t eat you. I couldn’t catch you. Look at me.'],
    shell: ['A rock. I’ll sit on it.', '…The rock is breathing. Iga rocks never did that.'],
    night: ['Can’t sleep. Every time I close my eyes I see the fires. So I watch this one instead.'],
    barks: {
      sit: ['Hm.', 'Another log on, child.', 'In Iga the mountains kept us safe. Until they didn’t.', '*cough* *cough*', 'Forty thousand. For farmers. He must have been very frightened of farmers.'],
    },
  },
  {
    id: 'oshizu',
    name: 'Oshizu',
    title: 'widow from Iga',
    home: 'door:tentB',
    color: '#9a7a6a',
    speed: 28,
    look: { hair: 'bun', hat: 'tenugui', robe: '#6a5a4a', robeShade: '#4e4236', sash: '#3a3030', legs: '#4e4236', collar: '#a89a80' },
    schedule: [
      asleep(),
      { at: '05:10', label: 'stoking the fire', doing: spot('campFireS', 'tend') },
      { at: '06:40', label: 'scrubbing barrels at the brewery, for rice', doing: spot('brewFront', 'sweep') },
      { at: '11:50', label: 'cooking thin gruel', doing: spot('campFireS', 'tend') },
      { at: '13:00', label: 'scrubbing barrels at the brewery, for rice', doing: spot('brewFront', 'sweep') },
      { at: '17:20', label: 'cooking supper (more gruel)', doing: spot('campFireS', 'tend') },
      home('20:30', 'mending by the last of the light'),
      asleep('21:30'),
    ],
    talk: [
      'Kurozaemon pays me in rice to scrub his barrels. Burnt rice, from the bottom of the pot. He calls it "generosity".',
      'My husband was a farmer. The soldiers said he was a ninja. Farmers are very easy to mistake for ninja, apparently. Especially dead ones.',
      'The village folk cross the road when they see us. As if losing everything were catching.',
      'Kotaro isn’t mine. He just turned up after the fires and never left. So now he’s mine.',
    ],
    turtle: ['A turtle! Kotaro, don’t— oh, he’s in the square. Good.', 'Go on, little turtle. There’s no food here. There’s barely us here.'],
    shell: ['A rock. Good. We need more rocks for the fire ring.', 'Oh. Sorry. Not a rock.'],
    barks: {
      tend: ['Gruel again.', 'Don’t go out tonight, fire. Please.', 'One more handful of rice in. No. Half.'],
      sweep: ['Scrub, scrub. For a bowl of burnt rice.', 'Sake barrels. I don’t even drink. Yet.', 'Yes, master Kurozaemon. Spotless, master Kurozaemon.'],
    },
  },
  {
    id: 'kotaro',
    name: 'Kotaro',
    title: 'orphan from Iga, beggar',
    home: 'door:tentC',
    color: '#b8a888',
    speed: 40,
    look: { kid: true, hair: 'kidBoy', robe: '#5a5048', robeShade: '#443c36', sash: '#2a2420', legs: '#f2c9a0' },
    schedule: [
      asleep(),
      { at: '06:20', label: 'begging in the square', doing: spot('beggarSpot', 'alms'), say: 'Alms for an orphan of Iga! Alms! …Anyone?' },
      { at: '11:50', label: 'chased off by the guards', doing: patrol(['southStreetW', 'mainStreetW', 'southStreetE'], undefined, 'stand', 6), say: 'I’m going, I’m going!' },
      { at: '13:00', label: 'begging in the square (again)', doing: spot('beggarSpot', 'alms') },
      { at: '16:30', label: 'throwing stones at crows', doing: chase('camp') },
      home('18:30', 'eating gruel'),
      asleep('20:30'),
    ],
    talk: [
      'Got a coin, turtle? No? Got a shell? …Can I have it?',
      'The guards chase me out of the square at noon. I come back at one. We both know the routine.',
      'I’m going to be a ninja. Everyone already thinks we are, so it’s basically free.',
      'Oshizu says I mustn’t steal. I don’t steal. Things just come with me.',
      'Hachi’s gang says the kappa in the duck pond eats Iga kids. Good. More fish for me.',
    ],
    turtle: ['A TURTLE! Can I keep you? I’ll call you Lord Shell. You can sleep in our tent. There’s room. There’s lots of room now.'],
    shell: ['A rock! A good throwing rock!', '…It has legs. Never mind. Sorry, Lord Shell.'],
    barks: {
      alms: ['Spare a coin? Spare a rice ball? Spare a smile? No?', 'Alms for an orphan of Iga!', 'You there! Samurai! You look generous! …You don’t, actually.', 'Thank you, auntie! …She gave me a radish. A radish.'],
      play: ['Take that, crow!', 'Kaa yourself!', 'One day I’ll hit one.'],
    },
  },
  {
    id: 'masa',
    name: 'Masa',
    title: 'deserter (don’t ask)',
    home: 'door:tentA',
    color: '#6a6a5a',
    speed: 28,
    look: { hair: 'short', hat: 'jingasa', robe: '#4a4a40', robeShade: '#36362e', sash: '#6a2a1e', legs: '#3a3a32', collar: '#6a6a5a', extras: ['swords'] },
    schedule: [
      { at: '00:00', label: 'keeping watch', doing: patrol(['campN', 'campEdge'], 'guard', 'guard', 25) },
      asleep('02:00'),
      { at: '10:00', label: 'chopping firewood', doing: spot('campEdge', 'hammer') },
      { at: '13:00', label: 'sitting apart from the others', doing: spot('campN', 'sit') },
      { at: '19:00', label: 'keeping watch', doing: patrol(['campN', 'campEdge'], 'guard', 'guard', 25) },
    ],
    talk: [
      'Last autumn I was in Iga too. On the other side. Don’t ask. I don’t.',
      'I keep watch at night. Old habit. These days I know what I’m watching for.',
      'The old man knows what I was. He still shares his fire. That’s worse than if he hit me.',
      'If the Oda come asking, you never saw me. You’re a turtle. You never see anything. Good.',
    ],
    turtle: ['…A turtle. Fine. You can stay. You’re the only one here who doesn’t look at me.'],
    shell: ['A rock that hides when people come close. I know the feeling.'],
    night: ['Go to sleep, turtle. I’ll watch. It’s the least I can do. Literally the least.'],
    barks: {
      guard: ['…', 'Quiet night. Quiet is good.', 'Who’s there? …Just the wind. It’s always just the wind.'],
      hammer: ['Chop.', 'Firewood. Honest work. First in years.'],
      sit: ['…'],
    },
  },
]
