// The harbour: fishermen, dockworkers, the fish market, the tavern, the harbour master — and the
// peddler who comes in from Sakai on market days.

import { asleep, home, patrol, spot, work, type VillagerSpec } from './types'

export const HARBOUR: VillagerSpec[] = [
  {
    id: 'sanpei',
    name: 'Sanpei',
    title: 'fisherman, teller of tall tales',
    home: 'door:fishhut',
    color: '#6f9fbf',
    speed: 28,
    look: { hair: 'short', hat: 'kasa', robe: '#6f9fbf', robeShade: '#4f7f9f', sash: '#7a5a42', legs: '#f2c9a0', collar: '#e8e0cc', extras: ['creel'] },
    schedule: [
      asleep(),
      { at: '04:00', label: 'fishing off the east pier', doing: spot('pierE', 'fish') },
      { at: '08:00', label: 'selling fish at the market', doing: spot('fishCounter2', 'shop'), say: 'Fresh bream! Caught this morning! Some of it!' },
      home('11:30', 'lunch'),
      { at: '13:00', label: 'fishing in the river', doing: spot('riverbank', 'fish') },
      { at: '17:00', label: 'fishing off the east pier', doing: spot('pierE', 'fish') },
      { at: '19:00', label: 'telling fish stories at the tavern', doing: spot('tavernFront', 'sit') },
      home('21:00'),
      asleep('21:30'),
    ],
    talk: [
      'Yesterday I caught a bream THIS big. It got away. It was bigger.',
      'The sea talks if you listen. Mostly it says "no fish today".',
      'You swim? Good. Tell the fish I’m a nice man.',
      'Old Tokubei says the giant carp was his. It was MINE. He was there. He was holding the bucket.',
    ],
    turtle: ['A swimmer! Don’t eat my bait.'],
    shell: ['Hm. Good shape for an anchor.'],
    barks: {
      fish: ['Bite… bite… bite…', 'Got one! …It’s a sandal.', 'Shh. You’ll scare the fish.'],
      shop: ['Bream! Mackerel! A fish that looks like Matabei!', 'This one fought like a samurai!'],
      sit: ['…and THEN the bream says—', 'It was THIS big. No. THIS big.'],
    },
  },
  {
    id: 'gennosuke',
    name: 'Gennosuke',
    title: 'harbour master',
    home: 'door:office',
    color: '#2f5a7a',
    speed: 26,
    look: { hair: 'topknot', robe: '#2f4a6a', robeShade: '#22364e', sash: '#c9b58a', legs: '#2a2233', collar: '#e8e0cc', extras: ['beard'] },
    schedule: [
      asleep(),
      { at: '05:00', label: 'watching the sea from the breakwater', doing: spot('breakwater', 'tend') },
      { at: '07:30', label: 'at the harbour office', doing: spot('officeFront', 'stand') },
      { at: '09:00', label: 'inspecting the piers', doing: patrol(['pierMidFoot', 'pierW', 'shipSide', 'pierE', 'officeFront'], undefined, 'tend', 8) },
      { at: '12:00', label: 'inspecting the "fast boat"', doing: spot('slipway', 'tend') },
      { at: '14:00', label: 'at the harbour office', doing: spot('officeFront') },
      { at: '17:00', label: 'watching the sea from the breakwater', doing: spot('breakwater', 'tend') },
      home('19:30'),
      asleep('22:00'),
    ],
    talk: [
      'Tides, winds, cargo, cats. The harbour runs on four things and I count all of them.',
      'Three boats from Iga last winter, full of people, no luggage. Captains charged them double. I logged it as "cargo".',
      'The fast boat? Just a precaution. For an important guest. Who may arrive. In a hurry. From the mountains. Forget I said that.',
      'I watch the sea every dawn and dusk. One day something will come over that horizon. Probably a fish.',
      'The ship captain says his ship is the fastest in Ise. My boat will be faster. It has to be.',
    ],
    turtle: ['A turtle. Swims well? Excellent. I may need a messenger. Hypothetically.'],
    shell: ['A stone on my breakwater. Unauthorised. I’ll let it go this once.'],
    barks: {
      tend: ['Wind from the west…', 'Tide’s turning.', 'Not today. Not yet.'],
      stand: ['Manifests, manifests…', 'Who parked that boat there?!'],
    },
  },
  {
    id: 'tatsu',
    name: 'Tatsu',
    title: 'dockworker',
    home: 'door:nagayaD',
    color: '#8a5a3a',
    speed: 30,
    look: { hair: 'short', hat: 'hachimaki', robe: '#5a6a7a', robeShade: '#44525e', sash: '#c0262f', legs: '#f2c9a0', collar: '#e8e0cc', extras: ['happi'] },
    schedule: [
      asleep(),
      { at: '05:30', label: 'unloading the merchant ship', doing: patrol(['shipSide', 'warehouseFront', 'pierMidFoot', 'harbourStreet'], 'carry', 'stand', 3) },
      { at: '12:00', label: 'lunch on the bales', doing: spot('quayW', 'sit') },
      { at: '13:00', label: 'loading rice bales', doing: work('docks', 'carry') },
      { at: '17:30', label: 'at the bathhouse', doing: spot('bathFront') },
      { at: '18:30', label: 'drinking at the tavern', doing: spot('tavernIn1', 'sit') },
      home('21:00'),
      asleep('21:30'),
    ],
    talk: [
      'Bale on, bale off. Bale on, bale off. I dream in bales.',
      'Kanta says he carries more than me. Kanta counts the same bale twice.',
      'The captain’s ship came in heavy. Rice, cotton, and one crate that meows. Nobody’s claimed the crate.',
    ],
    turtle: ['Out of the way, little shell! …Actually, you’re fine. You’re shorter than the bales.'],
    shell: ['Is this a bale? It’s not a bale. Kanta! Is this yours?'],
    barks: { carry: ['Hup!', 'Bale coming through!', 'Heavy one!'], walk: ['Bale coming through!'], sit: ['My back. My poor back.'] },
  },
  {
    id: 'kanta',
    name: 'Kanta',
    title: 'dockworker',
    home: 'door:nagayaC',
    color: '#7a6a3a',
    speed: 32,
    look: { hair: 'short', hat: 'hachimaki', robe: '#6a5a4a', robeShade: '#4e4236', sash: '#2f3f73', legs: '#f2c9a0', collar: '#e8e0cc', extras: ['happi'] },
    schedule: [
      asleep(),
      { at: '05:30', label: 'loading rice bales', doing: work('docks', 'carry') },
      { at: '12:00', label: 'lunch at the fish market', doing: spot('fishCounter', 'sit') },
      { at: '13:00', label: 'unloading the merchant ship', doing: patrol(['shipSide', 'warehouseFront', 'pierMidFoot', 'harbourStreet'], 'carry', 'stand', 3) },
      { at: '18:00', label: 'drinking at the tavern', doing: spot('tavernFront', 'sit') },
      home('21:00'),
      asleep('21:30'),
    ],
    talk: [
      'I carry more than Tatsu. I counted. Twice.',
      'One day I’ll be a sailor. Sailors carry nothing. They just point at things and shout.',
      'If you see a crate that meows, don’t open it. Last time I opened it, it was nine cats.',
    ],
    turtle: ['Ha! A turtle on the docks. Want a job? We pay in fish heads.'],
    shell: ['Tatsu, there’s a rock in the way. …Tatsu? TATSU.'],
    barks: { carry: ['Hup! Hup!', 'Coming through!', 'I’ve got it! I’ve… got it.'], sit: ['Fish heads again.'] },
  },
  {
    id: 'oshio',
    name: 'Oshio',
    title: 'fishwife, loudest voice in Ise',
    home: 'door:fishhut2',
    color: '#c06a4a',
    speed: 28,
    look: { hair: 'bun', hat: 'tenugui', robe: '#8a4a3a', robeShade: '#6a3628', sash: '#2f3f73', legs: '#3d3449', collar: '#f1e6cc', extras: ['apron'] },
    schedule: [
      asleep(),
      { at: '05:00', label: 'shouting prices at the fish market', doing: spot('fishCounter', 'shop'), say: 'FISH! FRESH FISH! BUY IT OR I’LL EAT IT MYSELF!', shout: true },
      { at: '11:30', label: 'selling fish in the square', doing: spot('fishStall', 'shop') },
      { at: '15:00', label: 'gutting fish on the quay', doing: spot('netMend', 'sit') },
      home('18:00'),
      asleep('21:00'),
    ],
    talk: [
      'BONITO! MACKEREL! …Oh, it’s you. Sorry, I only have the one volume.',
      'Hachi steals a fish a day. I let him steal the small ones. Don’t tell him.',
      'The cats have a union. They want three fish a day and holidays. I’m negotiating.',
    ],
    turtle: ['A TURTLE! …Not for sale. Shame. You’d look lovely on ice.'],
    shell: ['Is that rock for sale? Everything’s for sale.'],
    barks: { shop: ['FISH!', 'MACKEREL! CHEAP!', 'Don’t poke the octopus! It pokes back!'], sit: ['Gut, rinse, next.'] },
  },
  {
    id: 'mosuke',
    name: 'Mosuke',
    title: 'shipwright',
    home: 'door:shipwright',
    color: '#9a6a3a',
    speed: 28,
    look: { hair: 'topknot', hat: 'hachimaki', robe: '#7a5a3a', robeShade: '#5a4228', sash: '#3d3449', legs: '#3d3449', collar: '#c9b58a', extras: ['apron'] },
    schedule: [
      asleep(),
      { at: '06:00', label: 'building the fast boat', doing: work('shipwrightYard', 'hammer') },
      { at: '12:00', label: 'lunch on the slipway', doing: spot('slipway', 'sit') },
      { at: '13:00', label: 'building the fast boat', doing: work('shipwrightYard', 'hammer') },
      { at: '18:00', label: 'drinking at the tavern', doing: spot('tavernIn1', 'sit') },
      home('20:30'),
      asleep('21:00'),
    ],
    talk: [
      'The harbour master wants the fastest boat in Ise. By next week. I said: fast, good, cheap — pick two. He picked fast twice.',
      'A boat is a house that’s afraid of the ground.',
      'For whom? Nobody says. Someone important, in a hurry, maybe with a ninja. I just build it.',
    ],
    turtle: ['A turtle! Perfect hull shape. Nature knew what it was doing.'],
    shell: ['Hm. I could model a hull on that rock.'],
    barks: { hammer: ['Tok! Tok!', 'Faster, faster…', 'Plank, peg, pray.'], sit: ['Rice ball. Sea air. Good.'] },
  },
  {
    id: 'ofuna',
    name: 'Ofuna',
    title: 'net mender',
    home: 'door:fishhut2',
    color: '#8a9a7a',
    speed: 22,
    look: { hair: 'grayBun', hat: 'tenugui', robe: '#5a6a5a', robeShade: '#444f44', sash: '#c9b58a', legs: '#3d3449', collar: '#c9c1b0' },
    schedule: [
      asleep(),
      home('06:00', 'breakfast'),
      { at: '07:00', label: 'mending nets on the quay', doing: spot('netMend', 'sit') },
      { at: '12:00', label: 'gossiping with Oume', doing: spot('teaBench1', 'sit') },
      { at: '14:00', label: 'mending nets on the quay', doing: spot('quayE', 'sit') },
      home('18:00'),
      asleep('20:30'),
    ],
    talk: [
      'Every hole is a fish that got away. I close the holes. The fish complain.',
      'Sixty years of nets. My fingers know the knots better than my head knows my grandchildren.',
      'The fishermen lose the fish and blame my nets. My nets are perfect. The fishermen are not.',
    ],
    turtle: ['Oh, a turtle. Don’t get caught in my nets, dear. They’re for fish. And Sanpei’s sandal.'],
    shell: ['A stone. Good for holding nets down. Stay.'],
    barks: { sit: ['Over, under, through…', 'Another hole. Sanpei, I swear…', 'Hmm-hm-hmm.'] },
  },
  {
    id: 'kurobe',
    name: 'Captain Kurobe',
    title: 'master of the "Ise Maru"',
    home: 'door:inn',
    color: '#1e3a5a',
    speed: 28,
    look: { hair: 'topknot', robe: '#1e3a5a', robeShade: '#162a42', sash: '#e0b13c', legs: '#2a2233', collar: '#e0b13c', extras: ['beard', 'swords'] },
    schedule: [
      asleep(),
      home('07:00', 'breakfast at the inn'),
      { at: '08:30', label: 'checking his ship', doing: spot('shipSide', 'tend') },
      { at: '11:00', label: 'boasting in the square', doing: spot('squareBench1', 'sit') },
      { at: '13:00', label: 'haggling at the warehouses', doing: spot('warehouseFront') },
      { at: '16:00', label: 'checking his ship', doing: spot('shipSide', 'tend') },
      { at: '18:00', label: 'holding court at the tavern', doing: spot('tavernIn1', 'sit') },
      home('22:30', 'back at the inn'),
      asleep('23:00'),
    ],
    talk: [
      'The Ise Maru: fastest ship on the bay. Rice to Owari, cotton back, and once a very surprised whale.',
      'I’ve sailed to Sakai, to Hakata, and once very nearly to Korea. The wind had opinions.',
      'The harbour master’s building a "fast boat". Faster than mine? Ha! Ha. …How fast?',
    ],
    turtle: ['A sea turtle! Good omen for sailors! …Or bad. I always forget which.'],
    shell: ['A rock on the dock. That’s how you know you’re in a provincial harbour.'],
    barks: { tend: ['Good ship. Good girl.', 'Who scratched the paint?!'], sit: ['…and the whale says to me—', 'Another round! On the harbour master!'] },
  },
  {
    id: 'otaki',
    name: 'Otaki',
    title: 'keeper of the Drunken Octopus',
    home: 'door:tavern',
    color: '#c0262f',
    speed: 28,
    look: { hair: 'bun', robe: '#5a2a3a', robeShade: '#42202c', sash: '#e0b13c', legs: '#3d3449', collar: '#f1e6cc', extras: ['apron'] },
    schedule: [
      asleep(),
      home('09:00', 'cleaning up after last night'),
      { at: '12:00', label: 'buying fish', doing: spot('fishCounter2') },
      { at: '13:00', label: 'sweeping the harbour street', doing: { kind: 'area', area: 'harbourStreet', pose: 'sweep', style: 'wander' } },
      { at: '16:00', label: 'serving sake', doing: spot('tavernFront', 'serve'), say: 'The Octopus is open! Sake, grilled squid, and arguments!' },
      home('23:30', 'closing up'),
      asleep('01:00'),
    ],
    talk: [
      'Sailors, dockers, the odd samurai pretending not to be here. The Octopus takes everyone.',
      'A deserter drinks here sometimes. Pays in Oda coin and won’t say where he got it. I don’t ask. That’s the whole job.',
      'The octopus on the sign? My late husband painted it. He was drunk too. It’s a tribute.',
      'Kurozaemon says he only comes here for "research". He researches six cups a night.',
    ],
    turtle: ['A turtle in the Octopus! Sit, sit. First cup is free. For turtles. Today only.'],
    shell: ['Somebody left a rock. It’s not the strangest thing left here. Top ten, though.'],
    barks: { serve: ['Sake! Hot or cold?', 'Grilled squid!', 'No fighting! Outside! …Not THAT outside, the sea’s there!'], sweep: ['Squid skewers everywhere…'] },
  },
  {
    id: 'jinbei',
    name: 'Jinbei',
    title: 'travelling peddler (market days)',
    home: 'westEdge',
    color: '#b08a50',
    speed: 28,
    look: { hair: 'topknot', hat: 'kasa', robe: '#8a6a40', robeShade: '#6a4f2e', sash: '#3d3449', legs: '#3d3449', collar: '#e8e0cc', extras: ['backpack'] },
    schedule: [
      { at: '00:00', label: 'on the road from Sakai', doing: { kind: 'inside', lit: true } },
      { at: '07:30', label: 'selling at the market', doing: spot('stall', 'shop'), days: 'market', say: 'Market day! Combs from Kyoto! Fans from Sakai! Rumours from everywhere!', shout: true },
      { at: '15:30', label: 'resting his feet', doing: spot('teaBench4', 'sit'), days: 'market' },
      { at: '16:30', label: 'a drink before the road', doing: spot('tavernFront', 'sit'), days: 'market' },
      { at: '18:00', label: 'on the road to Sakai', doing: { kind: 'inside', lit: true }, days: 'market' },
    ],
    talk: [
      'Combs from Kyoto! Fans from Sakai! Rumours from everywhere!',
      'I hear the capital is restless. Lord Nobunaga at Honnō-ji, Lord Akechi’s army "passing by". Bad for business.',
      'A turtle-shell comb? No offence. Purely hypothetical.',
      'I walked from Sakai. Five days. You’d take… a while.',
    ],
    turtle: ['A customer with a shell! I have just the polishing cloth.'],
    shell: ['Excellent stone. I could sell this.'],
    barks: {
      shop: ['Fans! Combs! Needles! A rare tea bowl, only slightly broken!', 'Everything must go! Including me, at six.'],
      sit: ['My feet have walked to Kyoto and back. They want a divorce.'],
    },
  },
]

