// The temple on the hill, and the old man on the island.

import { asleep, home, spot, wander, work, type VillagerSpec } from './types'

export const TEMPLE: VillagerSpec[] = [
  {
    id: 'kakuzen',
    name: 'Kakuzen',
    title: 'mountain monk (yamabushi)',
    home: 'door:hut',
    color: '#e0d6b0',
    speed: 26,
    look: { hair: 'bald', hat: 'tokin', robe: '#e2d8b4', robeShade: '#b9ad86', sash: '#6a4a8a', legs: '#e2d8b4', collar: '#c0262f', extras: ['pompoms'] },
    schedule: [
      asleep(),
      { at: '05:30', label: 'blowing the conch over the town', doing: spot('stairsTop', 'conch') },
      { at: '06:15', label: 'meditating by the pagoda', doing: spot('pagodaFront', 'meditate') },
      { at: '09:00', label: 'begging alms in the square', doing: spot('notice', 'alms') },
      { at: '12:00', label: '"meditating" (napping) at the shrine', doing: spot('inariFront', 'nap') },
      { at: '14:30', label: 'blessing the fishing boats', doing: spot('pierMidFoot', 'chant') },
      { at: '17:00', label: 'climbing back up the hill', doing: spot('stairsMid', 'stand') },
      home('18:00', 'in his hut'),
      asleep('20:30'),
    ],
    talk: [
      'I am a yamabushi. I sleep on mountains. Sometimes in the middle of sweeping.',
      'The rooster and I compete every dawn. I have the conch. He has no shame.',
      'Every being has the Buddha nature. Even crows. Even seagulls. Gonbei disagrees about both.',
      'Patience is the root of safety. Also of naps.',
    ],
    turtle: ['Ah. The turtle carries its home. Very wise. Very slow.'],
    shell: ['The turtle withdraws from the world. I respect that. I envy that.'],
    barks: {
      conch: ['BWOOOOOOOO!'],
      chant: ['Namu Amida Butsu…', 'May your nets be full and your boats be dry.'],
      nap: ['Zzz… I’m meditating… zzz…'],
      alms: ['Alms for a humble monk? Rice? Coin? Sake?'],
      meditate: ['The pagoda sways. The mind does not. The stomach does.'],
      stand: ['108 steps. 108 worldly desires. 109 if you count wanting to stop.'],
    },
  },
  {
    id: 'ryonen',
    name: 'Abbot Ryōnen',
    title: 'abbot of Kōun-ji',
    home: 'door:kuri',
    color: '#2a2233',
    speed: 22,
    look: { hair: 'bald', robe: '#2a2233', robeShade: '#1a1622', sash: '#e0b13c', legs: '#2a2233', collar: '#e8e0cc', extras: ['kesa'] },
    schedule: [
      asleep(),
      { at: '04:30', label: 'morning sutras in the main hall', doing: spot('hondoFront', 'chant') },
      home('07:00', 'breakfast (rice, pickles, silence)'),
      { at: '08:00', label: 'tending the graves', doing: wander('graveyard', 'tend') },
      { at: '10:30', label: 'receiving pilgrims', doing: spot('incense', 'stand') },
      { at: '13:00', label: 'composing a sermon by the pond', doing: spot('templePond', 'meditate') },
      { at: '16:00', label: 'evening sutras', doing: spot('hondoFront', 'chant') },
      home('18:30'),
      asleep('21:00'),
    ],
    talk: [
      'All things are impermanent. Castles, lords, rice prices. Mostly rice prices.',
      'We buried six from the camp this spring. They had no money for prayers. I said them anyway. The Buddha doesn’t keep accounts. The temple does.',
      'A turtle at the temple. In the old stories you’d carry the world on your back. Today you may carry yourself.',
      'Lord Nobunaga burned Mount Hiei. Monks remember. But we are told to forgive. We are working on it.',
      'Kakuzen naps at noon and calls it meditation. I nap at one and call it the afternoon sutra.',
    ],
    turtle: ['Welcome, small pilgrim. You climbed 108 steps. Or swam. Either is an achievement.'],
    shell: ['The turtle hides in its shell; the monk hides in his robes. We are both very calm.'],
    barks: { chant: ['Namu Amida Butsu…', 'Form is emptiness… emptiness is form…'], tend: ['Rest well.', 'Fresh flowers today.'], meditate: ['Hmm.'] },
  },
  {
    id: 'anko',
    name: 'Ankō',
    title: 'novice monk, sweeper of stairs',
    home: 'door:kuri',
    color: '#7a6a8a',
    speed: 30,
    look: { kid: true, hair: 'bald', robe: '#4a4058', robeShade: '#36304a', sash: '#c9b58a', legs: '#4a4058' },
    schedule: [
      asleep(),
      { at: '05:50', label: 'ringing the great bell', doing: spot('bell', 'tend'), say: 'GONNNNNNG…', shout: true },
      { at: '06:10', label: 'sweeping the 108 steps', doing: work('stairs', 'sweep') },
      { at: '10:00', label: 'raking the temple gravel', doing: work('templeGrounds', 'sweep') },
      { at: '12:00', label: 'lunch', doing: { kind: 'inside', lit: true } },
      { at: '13:00', label: 'sweeping the 108 steps (again)', doing: work('stairs', 'sweep') },
      { at: '17:50', label: 'ringing the great bell', doing: spot('bell', 'tend'), say: 'GONNNNNNG…', shout: true },
      home('18:20', 'dinner and sutras'),
      asleep('21:00'),
    ],
    talk: [
      'One hundred and eight steps. I sweep them every morning. Every afternoon the leaves come back. This is my teaching.',
      'Step 52 creaks. Gorō says it hates him. I think it hates everyone.',
      'The abbot says enlightenment comes when you stop counting the steps. I’m on step 74.',
    ],
    turtle: ['A turtle climbed the stairs! …How?! It takes ME all morning and I have legs!'],
    shell: ['Did you come up the stairs? Or were you always here? Is this a koan?'],
    barks: { sweep: ['Fifty-one… fifty-two (creak)… fifty-three…', 'Leaves. Always leaves.', 'This is my teaching. This is my teaching.'], tend: ['GONNNG…'] },
  },
  {
    id: 'roshi',
    name: 'Master Roshi',
    title: 'hermit, your boss',
    home: 'roshiDoor',
    color: '#f0a030',
    speed: 18,
    look: { hair: 'bald', robe: '#f0a030', robeShade: '#c67a1c', sash: '#7a4ea3', legs: '#f2c9a0', collar: '#f6f2e8', extras: ['beard', 'shades', 'shell'] },
    schedule: [
      asleep(),
      { at: '06:00', label: 'seeing the turtle off (shouting)', doing: spot('roshiShore', 'stand') },
      home('08:00', 'reading (do not ask what)'),
      { at: '09:00', label: 'napping in his beach chair', doing: spot('roshiChair', 'nap') },
      { at: '12:00', label: 'staring at the town, thirsty', doing: spot('roshiShore', 'stand') },
      { at: '13:00', label: 'napping in his beach chair', doing: spot('roshiChair', 'nap') },
      { at: '16:00', label: 'doing "exercises"', doing: wander('island', 'stand') },
      home('19:00', 'reading (still do not ask)'),
      asleep('22:00'),
    ],
    talk: [
      'Hohoho! Back already? Where’s my sake? …No sake? Then why are you back?',
      'Grim times, turtle. Lords burning provinces, kappa in the moat, sake prices up. The sake prices are the real tragedy.',
      'Kurozaemon won’t sell? Tell him I paid! …Tell him I’ll pay. Tell him something.',
      'Three hundred years I’ve lived on this island. The view gets better every century. The sake gets further away.',
      'If you see Kiyo on the farm, don’t mention me. If she asks, I’m dead. Handsome, but dead.',
      'Swim, turtle! Swim! Ten thousand years of life and you spend it standing on my beach!',
    ],
    turtle: ['Hohoho! My turtle! Did you bring the sake?'],
    shell: ['Don’t hide in your shell, I can see you. I invented hiding in shells.'],
    night: ['Zzz… sake… zzz… Kiyo… zzz…'],
    barks: {
      nap: ['Zzz…', 'Zzz… sake… zzz…', 'Hohoho… zzz…'],
      stand: ['Hmm. That brewery looks very close today.', 'Turtle! TURTLE! …Sake!'],
      walk: ['Hup, two, three… hup… enough exercise.'],
    },
  },
]

