// Townsfolk inside the walls: shopkeepers, craftsmen, guards, samurai, and the night watchman.

import { asleep, home, patrol, spot, wander, work, type VillagerSpec } from './types'

const GUARD_LOOK = { hair: 'topknot', hat: 'jingasa', robe: '#3d3449', robeShade: '#2a2233', sash: '#c0262f', legs: '#3d3449', collar: '#c0262f', extras: ['armor', 'banner'] } as const

export const TOWN: VillagerSpec[] = [
  {
    id: 'oume',
    name: 'Oume',
    title: 'teahouse keeper, gossip merchant',
    home: 'door:teahouse',
    color: '#9a3f62',
    speed: 28,
    look: { hair: 'bun', robe: '#8a3f5a', robeShade: '#682e44', sash: '#e0b13c', legs: '#3d3449', collar: '#f1e6cc', extras: ['apron'] },
    schedule: [
      asleep(),
      { at: '06:00', label: 'sweeping the front', doing: { kind: 'area', area: 'teaFront', pose: 'sweep', style: 'wander' } },
      { at: '07:00', label: 'serving tea', doing: spot('teaCounter', 'serve'), say: 'Teahouse is open! Tea, dango, gossip!' },
      home('21:30', 'counting the day’s coins'),
      asleep('23:00'),
    ],
    talk: [
      'Welcome, welcome! Tea? Dango? Gossip? The gossip is free.',
      'The Iga people outside the gate? Poor things. Mind you, I lock my door now. I always did. But now I mean it.',
      'Did you hear? Lord Nobunaga is staying at Honnō-ji in Kyoto with hardly any guards. What could possibly go wrong?',
      'The harbour master ordered a fast boat "for an important guest". Important guests don’t usually need FAST boats, dear.',
      'Kurozaemon won’t sell to the island hermit. Unpaid tab. Three hundred years of it.',
      'You don’t talk? Even better. You’ll keep all my secrets.',
    ],
    turtle: ['Oh my! A guest with a shell! Sit anywhere, dear!'],
    shell: ['Ara, a decorative stone. How tasteful.'],
    barks: {
      serve: ['Tea’s hot! Mind your shell.', 'Dango! Fresh dango!', 'Another cup, Gonbei? Of course another cup.', 'Ara ara… did you hear about…'],
      sweep: ['Sweep, sweep. The dust always comes back. So do the customers.'],
    },
  },
  {
    id: 'kurozaemon',
    name: 'Kurozaemon',
    title: 'master brewer',
    home: 'door:brewery',
    color: '#d8d0b8',
    speed: 28,
    look: { hair: 'topknot', hat: 'hachimaki', robe: '#e7e0cf', robeShade: '#bdb39c', sash: '#2f3f73', legs: '#2f3f73', collar: '#2f3f73', extras: ['happi'] },
    schedule: [
      asleep(),
      home('04:30', 'brewing (inside, steaming)'),
      { at: '07:00', label: 'hauling casks', doing: work('brewYard', 'carry') },
      { at: '12:00', label: 'lunch at the teahouse', doing: spot('teaBench3', 'sit') },
      { at: '13:00', label: 'hauling casks', doing: work('brewYard', 'carry') },
      home('16:00', 'tasting (quality control)'),
      { at: '19:00', label: '"research" at the tavern', doing: spot('tavernFront', 'sit') },
      home('21:00'),
      asleep('22:00'),
    ],
    talk: [
      'Best sake in Ise. Do not tell me Owari has better sake. Owari has better LIARS.',
      'I pay that Iga widow in rice to scrub my barrels. People call me generous. I let them.',
      'The island hermit? His tab is older than my grandfather. NO sake for his errand turtle.',
      'Green cedar ball: the new sake is ready. Brown: the sake is perfect. Fallen off: I drank it.',
      'No turtles in the brewery. The last turtle in the brewery… we don’t talk about the last turtle.',
    ],
    turtle: ['You! Turtle! I know who sent you!', 'Keep your flippers off my casks.'],
    shell: ['A rock. Next to my casks. Suspicious rock.'],
    barks: {
      carry: ['Hup!', 'Mind the cask!', 'This one’s for the castle. Allegedly.'],
      sit: ['Aah. Somebody else’s sake. Professional research.'],
    },
  },
  {
    id: 'heisuke',
    name: 'Heisuke',
    title: 'Sea Gate guard (ashigaru)',
    home: 'door:nagayaD',
    color: '#c0262f',
    speed: 32,
    look: { ...GUARD_LOOK, extras: [...GUARD_LOOK.extras] },
    schedule: [
      { at: '00:00', label: 'night watch at the Sea Gate', doing: spot('seaGateNight', 'guard') },
      asleep('02:00'),
      { at: '07:00', label: 'guarding the Sea Gate', doing: spot('seaGateGuard', 'guard') },
      { at: '12:00', label: 'lunch (vigilantly)', doing: spot('teaBench4', 'sit') },
      { at: '13:00', label: 'guarding the Sea Gate', doing: spot('seaGateGuard', 'guard') },
      { at: '15:00', label: 'a five-minute dango break', doing: spot('teaBench1', 'sit') },
      { at: '16:10', label: 'patrolling the harbour', doing: patrol(['seaGateNight', 'officeFront', 'tavernFront', 'warehouseFront', 'quayE']) },
      home('18:30', 'dinner'),
      { at: '20:00', label: 'night watch at the Sea Gate', doing: spot('seaGateNight', 'guard'), say: 'Night watch! Nobody passes without… asking nicely.' },
    ],
    talk: [
      'I guard the Sea Gate. Things that come from the sea: fish, sailors, and once a very angry octopus.',
      'One day I’ll have real armour. Lacquered. With a big crest. A moon. Or a turtle!',
      'If anyone asks, I’ve been guarding all day. Especially at the teahouse.',
      'They say Akechi soldiers are on the roads. I’m not scared. You’re scared.',
    ],
    turtle: ['HALT! …It’s a turtle. Stand down, Heisuke.', 'Are you an Akechi spy? Blink once for no.'],
    shell: ['It’s a trap. Rocks don’t sweat.'],
    night: ['Who’s there?! …The wind. Good. Good wind.'],
    barks: {
      guard: ['Halt! Who goes— oh. Nobody.', 'Nothing to report. Except that seagull.', 'The gate is secure. I checked it. Twice.'],
      walk: ['Left, right, left…', 'All quiet. Suspiciously quiet.'],
      sit: ['Just one dango. For vigilance.'],
    },
  },
  {
    id: 'rokusuke',
    name: 'Rokusuke',
    title: 'West Gate guard (ashigaru)',
    home: 'door:nagayaA',
    color: '#a0303a',
    speed: 30,
    look: { ...GUARD_LOOK, robe: '#4a3a3a', extras: ['armor'] },
    schedule: [
      asleep(),
      { at: '06:00', label: 'guarding the West Gate', doing: spot('westGateGuard', 'guard') },
      { at: '12:30', label: 'lunch at the bathhouse steps', doing: spot('bathFront', 'sit') },
      { at: '13:30', label: 'guarding the West Gate', doing: spot('westGateGuard', 'guard') },
      { at: '19:00', label: 'drinking at the tavern', doing: spot('tavernIn1', 'sit') },
      home('21:30'),
      asleep('22:00'),
    ],
    talk: [
      'West Gate. Road to Sakai. Five days of walking, then a city full of merchants who all want your money.',
      'Orders are: Iga folk stay outside the West Gate after dark. I open it a crack for the boy anyway. Don’t tell the captain.',
      'A peddler came through with "news from Kyoto". Ten coppers for news! I said I’d wait for it to get cheaper.',
      'Matabei on the East Gate sleeps all day. I sleep only half the day. That’s called discipline.',
    ],
    turtle: ['Halt! State your business! …Sake? Fair enough. Pass.'],
    shell: ['Is this rock a traveller? Does it have papers?'],
    barks: { guard: ['West Gate, all quiet.', 'Papers? …You’re a cart of radishes. Go on.'], sit: ['Ahh. Hot feet. Cold sake.'] },
  },
  {
    id: 'matabei',
    name: 'Matabei',
    title: 'East Gate guard (mostly asleep)',
    home: 'door:nagayaB',
    color: '#803038',
    speed: 24,
    look: { ...GUARD_LOOK, robe: '#3a3a4a', extras: ['armor'] },
    schedule: [
      asleep(),
      { at: '06:30', label: 'guarding the East Gate', doing: spot('eastGateGuard', 'guard') },
      { at: '09:00', label: '"guarding" the East Gate', doing: spot('eastGateGuard', 'nap') },
      { at: '12:00', label: 'lunch', doing: spot('squareBench1', 'sit') },
      { at: '13:00', label: '"guarding" the East Gate', doing: spot('eastGateGuard', 'nap') },
      { at: '16:30', label: 'guarding the East Gate', doing: spot('eastGateGuard', 'guard') },
      home('19:00'),
      asleep('20:00'),
    ],
    talk: [
      'Zzz… huh? I’m awake. I’m very awake. I’m guarding with my eyes closed. Advanced technique.',
      'East road goes to Okazaki. Lord Tokugawa’s country. Very serious people. Very little napping.',
      'If bandits come, I’ll be ready. I’ll be asleep, but ready.',
    ],
    turtle: ['Whoa! …Oh. A turtle. I thought I was dreaming. I usually am.'],
    shell: ['A rock. I’ll lean on it. Nap station.'],
    barks: { nap: ['Zzz…', 'Zzz… five more minutes…', '…mmh… dango…'], guard: ['East Gate. Awake. Very.'] },
  },
  {
    id: 'sakuma',
    name: 'Sakuma Gendayū',
    title: 'samurai, captain of the guard',
    home: 'door:samuraiSakuma',
    color: '#2f3f73',
    speed: 30,
    look: { hair: 'topknot', robe: '#2f3f73', robeShade: '#22305a', sash: '#c9b58a', legs: '#5a5a6a', collar: '#e8e0cc', extras: ['swords', 'hakama'] },
    schedule: [
      asleep(),
      { at: '05:30', label: 'sword practice', doing: spot('samuraiLane', 'hammer') },
      home('07:00', 'breakfast'),
      { at: '08:00', label: 'inspecting the gates', doing: patrol(['northGateGuard', 'westGateGuard', 'seaGateGuard', 'eastGateGuard', 'castleGateGuard']) },
      { at: '12:00', label: 'reporting at the castle', doing: spot('castleSteps') },
      { at: '13:00', label: 'tea with the steward', doing: spot('teaBench3', 'sit') },
      { at: '14:30', label: 'inspecting the harbour', doing: patrol(['officeFront', 'shipSide', 'warehouseFront', 'tavernFront']) },
      home('18:00'),
      asleep('22:00'),
    ],
    talk: [
      'I am Sakuma Gendayu, captain of the guard. You are a turtle. We both know our places.',
      'I was at Iga last autumn. We were told they were ninja. The ones I saw were holding hoes. I have stopped telling that story at dinner.',
      'The guards are lazy, the gates creak, and the harbour master is hiding something. A normal week.',
      'A samurai must be ready for anything. Except turtles. Nobody trained me for turtles.',
    ],
    turtle: ['A turtle, inside the walls. Write it down. No — don’t write it down.'],
    shell: ['Hm. A rock that was not there this morning. I shall investigate. Later.'],
    barks: { hammer: ['Hah!', 'Hyah!', 'One thousand cuts. Nine hundred and ninety-nine to go.'], walk: ['Gates. Guards. Gates.'], sit: ['The tea is acceptable.'] },
  },
  {
    id: 'chiyo',
    name: 'Lady Chiyo',
    title: 'samurai’s wife, poet',
    home: 'door:samuraiSakuma',
    color: '#b05a8a',
    speed: 24,
    look: { hair: 'bun', robe: '#a04a7a', robeShade: '#7a345c', sash: '#e0b13c', legs: '#3d3449', collar: '#f1e6cc' },
    schedule: [
      asleep(),
      home('06:00', 'arranging flowers'),
      { at: '09:00', label: 'praying at the temple', doing: spot('hondoSide', 'chant') },
      { at: '11:00', label: 'composing poems by the pond', doing: spot('templePond', 'sit') },
      { at: '13:00', label: 'shopping for cloth', doing: spot('clothFront') },
      { at: '14:00', label: 'tea and poetry', doing: spot('teaBench4', 'sit') },
      home('16:30'),
      asleep('22:00'),
    ],
    talk: [
      'A turtle at dusk — / carrying its home, unhurried — / the samurai runs.',
      'My husband says poetry is a waste of ink. I said war is a waste of samurai. We had a long silence.',
      'The pagoda at dawn is the most beautiful thing in Ise. The second is a well-made sweet bean cake.',
    ],
    turtle: ['Oh! A turtle. That’s a poem. Hold still.'],
    shell: ['A stone in the road — / it breathes, and the stone watches — / I will not tell him.'],
    barks: { sit: ['Five, seven, five… five, seven…', 'The pond, the frog, the… no, that’s been done.'], chant: ['Namu…'] },
  },
  {
    id: 'iori',
    name: 'Iori',
    title: 'castle steward',
    home: 'door:samuraiIori',
    color: '#4a4a6a',
    speed: 30,
    look: { hair: 'topknot', robe: '#4a4a5a', robeShade: '#36364a', sash: '#2a2233', legs: '#6a6a7a', collar: '#e8e0cc', extras: ['swords', 'hakama'] },
    schedule: [
      asleep(),
      { at: '06:00', label: 'at the castle', doing: spot('castleYard') },
      { at: '09:00', label: 'checking the stable', doing: spot('stableFront', 'tend') },
      { at: '10:00', label: 'at the harbour office', doing: spot('officeFront') },
      { at: '11:30', label: 'counting rice at Rihei’s', doing: spot('riceFront') },
      { at: '13:00', label: 'tea with the captain', doing: spot('teaBench2', 'sit') },
      { at: '14:30', label: 'at the castle', doing: wander('castleYard') },
      home('18:00'),
      asleep('22:30'),
    ],
    talk: [
      'The lord is in Kyoto with Lord Nobunaga. I keep the castle. I also keep the keys, the books and the blame.',
      'The burnt house on Brewery Street? A cooking fire. Officially. The owner owed the castle money. Unofficially, also a cooking fire.',
      'The harbour master wants the fastest boat in Ise kept ready. For whom? He says "you’ll see". I hate "you’ll see".',
      'Rice in the warehouses, coin in the strongbox, turtle in the square. Two out of three is normal.',
    ],
    turtle: ['A turtle. Is it taxed? Everything is taxed. I’ll look it up.'],
    shell: ['A stone. Unregistered. Typical.'],
    barks: { stand: ['Hmm. Hmm. Hmm.', 'Ledgers, ledgers…'], sit: ['The captain talks; I count.'] },
  },
  {
    id: 'rihei',
    name: 'Rihei',
    title: 'rice merchant',
    home: 'door:riceShop',
    color: '#c9b58a',
    speed: 26,
    look: { hair: 'topknot', robe: '#6a5a3a', robeShade: '#4e4228', sash: '#2a2233', legs: '#3d3449', collar: '#e8e0cc' },
    schedule: [
      asleep(),
      { at: '06:00', label: 'counting rice bales', doing: spot('riceFront', 'shop') },
      { at: '10:30', label: 'haggling at the warehouses', doing: spot('warehouseFront') },
      { at: '12:30', label: 'counting rice bales', doing: spot('riceFront', 'shop') },
      home('18:00', 'counting coins'),
      asleep('22:00'),
    ],
    talk: [
      'Rice is money. Literally. Samurai are paid in rice. I am the bank, but with more mice.',
      'Two hundred and twelve bales. No — two hundred and eleven. Yasaku! Where’s the bale?!',
      'If the lord ever comes home from Kyoto, rice prices will go up. If he doesn’t, they’ll go up anyway.',
    ],
    turtle: ['A turtle. Do turtles eat rice? No? Then I have nothing to say to you.'],
    shell: ['A stone. Could it hold a bale? Hm.'],
    barks: { shop: ['Two hundred and nine… two hundred and ten…', 'Rice! Polished! Unpolished! Gossiped about!'] },
  },
  {
    id: 'osen',
    name: 'Osen',
    title: 'cloth merchant',
    home: 'door:clothShop',
    color: '#5a74a8',
    speed: 28,
    look: { hair: 'bun', robe: '#5a74a8', robeShade: '#435a88', sash: '#f0a0b8', legs: '#3d3449', collar: '#f1e6cc' },
    schedule: [
      asleep(),
      { at: '07:00', label: 'selling cloth', doing: spot('clothFront', 'shop') },
      { at: '12:00', label: 'lunch at the teahouse', doing: spot('teaBench2', 'sit') },
      { at: '13:00', label: 'selling cloth', doing: spot('clothFront', 'shop') },
      { at: '17:30', label: 'at the bathhouse', doing: spot('bathFront') },
      home('19:00'),
      asleep('22:00'),
    ],
    talk: [
      'Indigo from Tokushima, silk from Kyoto, cotton from Owari. And this pink. I don’t know where the pink came from.',
      'Lady Chiyo buys a new kimono every month. Her husband buys a new sword every month. They never discuss money.',
      'A turtle with a red scarf! Very bold. You should model for me.',
    ],
    turtle: ['Oh! That scarf! Is that Kyoto red? It’s Kyoto red.'],
    shell: ['That stone has a lovely green. I could dye a kimono that colour.'],
    barks: { shop: ['Cloth! Fine cloth!', 'This pink? …It’s bold.', 'Indigo! Never fades! Mostly!'] },
  },
  {
    id: 'heikichi',
    name: 'Heikichi',
    title: 'tofu maker',
    home: 'door:tofu',
    color: '#e8e4dc',
    speed: 30,
    look: { hair: 'short', hat: 'hachimaki', robe: '#d8d0c0', robeShade: '#b0a890', sash: '#3d3449', legs: '#3d3449', collar: '#2f3f73', extras: ['apron'] },
    schedule: [
      asleep(),
      home('03:00', 'making tofu (since 3 a.m.)'),
      { at: '06:00', label: 'selling tofu round the streets', doing: patrol(['tofuFront', 'mainStreetE', 'samuraiLane', 'mainStreetW', 'southStreetW', 'southStreetE'], 'carry', 'call', 2), say: 'Tō-fuuu! Tofuuu!' },
      { at: '10:00', label: 'selling tofu at the shop', doing: spot('tofuFront', 'shop') },
      home('14:00', 'asleep (it’s been a long day)'),
      asleep('15:00'),
    ],
    talk: [
      'I get up at three. Tofu waits for no one. Tofu doesn’t even wait for the sun.',
      'Soft tofu, firm tofu, fried tofu for the Inari foxes. The foxes never pay.',
      'You’re a turtle. You’d like tofu. Everybody likes tofu. Except the foxes, apparently.',
    ],
    turtle: ['Tofu? For the turtle? …No coins? Hm. One cube. Don’t tell anyone.'],
    shell: ['Is that a stone, or very old tofu? …Stone.'],
    barks: { call: ['Tō-fuuu!', 'Tofu! Tofuuu!'], carry: ['Tō-fuuu!'], walk: ['Tō-fuuu!'], shop: ['Fresh tofu! Made before you woke up!'] },
  },
  {
    id: 'yohei',
    name: 'Yohei',
    title: 'sweets maker',
    home: 'door:sweetShop',
    color: '#f0a0b8',
    speed: 28,
    look: { hair: 'topknot', robe: '#c47a9a', robeShade: '#9a5a78', sash: '#f1e6cc', legs: '#3d3449', collar: '#f1e6cc', extras: ['apron'] },
    schedule: [
      asleep(),
      home('05:00', 'boiling sweet beans'),
      { at: '08:00', label: 'selling sweets', doing: spot('sweetFront', 'shop') },
      { at: '13:00', label: 'selling dango to pilgrims', doing: spot('dangoFront', 'shop') },
      home('17:30'),
      asleep('21:30'),
    ],
    talk: [
      'Sweet bean paste, mochi, dango in three colours. The three colours are spring, summer and "more sugar".',
      'The pilgrims climb the temple stairs, then come down and buy dango. I am the reward for virtue.',
      'Oume sells my dango at her teahouse and says she makes them. I let her. It’s called love.',
    ],
    turtle: ['A turtle! Do turtles like mochi? Careful, it’s sticky. Very sticky. Ask the last turtle.'],
    shell: ['That rock is the shape of a manjū. I’m hungry.'],
    barks: { shop: ['Dango! Three colours!', 'Mochi! Pounded this morning!', 'Sweets for the climb!'] },
  },
  {
    id: 'oyone',
    name: 'Oyone',
    title: 'bathhouse keeper',
    home: 'door:bathhouse',
    color: '#6a9ac8',
    speed: 28,
    look: { hair: 'bun', hat: 'tenugui', robe: '#4a7aa8', robeShade: '#365a80', sash: '#f1e6cc', legs: '#3d3449', collar: '#f1e6cc' },
    schedule: [
      asleep(),
      { at: '06:30', label: 'sweeping the street', doing: { kind: 'area', area: 'mainStreet', pose: 'sweep', style: 'wander' } },
      home('08:00', 'heating the baths'),
      { at: '14:00', label: 'taking coins at the door', doing: spot('bathFront', 'shop'), say: 'The bath is hot! Six coppers! Turtles… we’ll discuss it.' },
      home('22:00', 'scrubbing the tubs'),
      asleep('23:30'),
    ],
    talk: [
      'Everyone’s equal in the bathhouse. Samurai, fishermen, merchants. Everyone’s naked and everyone gossips.',
      'Turtles in the bath? There’s no rule. There will be a rule.',
      'The fishermen come in smelling of fish and leave smelling of… slightly less fish. That’s my art.',
    ],
    turtle: ['A turtle at my door! Are you dirty? You look dirty. You’re a turtle, you can’t help it.'],
    shell: ['A rock by my door. Good for scrubbing feet.'],
    barks: { shop: ['Hot bath! Hot bath!', 'Six coppers. Towel extra.', 'No splashing!'], sweep: ['Sweep, sweep.'] },
  },
  {
    id: 'danjuro',
    name: 'Danjūrō',
    title: 'fortune teller',
    home: 'door:nagayaA',
    color: '#6a4a8a',
    speed: 24,
    look: { hair: 'grayBun', hat: 'kasa', robe: '#4a3a6a', robeShade: '#36284e', sash: '#e0b13c', legs: '#2a2233', collar: '#e0b13c' },
    schedule: [
      asleep(),
      home('07:00', 'consulting the stars (sleeping in)'),
      { at: '10:00', label: 'telling fortunes', doing: spot('fortune', 'sit') },
      { at: '17:00', label: 'telling fortunes at the tavern', doing: spot('tavernIn1', 'sit') },
      home('21:30'),
      asleep('22:30'),
    ],
    talk: [
      'Your fortune: a long journey. Slow. Very slow. You will arrive. Eventually.',
      'I see a great lord… in a temple… on fire. In Kyoto. Soon. That’ll be two coppers. No, I don’t know which lord. Two coppers.',
      'I see… a great lord… a temple… fire… …no, sorry, that’s my lunch burning.',
      'I see a boat in the night. An important guest. Very nervous. A ninja! …That’s twenty coppers.',
      'Everything I predict comes true eventually. I just don’t say when. That’s the trick.',
    ],
    turtle: ['Ah! I foresaw you! …I foresaw "a visitor". You count.'],
    shell: ['Even the stone has a destiny. This one’s destiny is to be stepped on.'],
    barks: { sit: ['The sticks say… "maybe".', 'Fortunes! Good ones cost extra!', 'Beware the second day of the sixth month! …Or the third. One of those.'] },
  },
  {
    id: 'soan',
    name: 'Sōan',
    title: 'town doctor',
    home: 'door:doctor',
    color: '#3a5a4a',
    speed: 30,
    look: { hair: 'bald', robe: '#2a3a32', robeShade: '#1e2a24', sash: '#5a8a6a', legs: '#2a2233', collar: '#c9c1b0' },
    schedule: [
      asleep(),
      { at: '07:00', label: 'selling medicine', doing: spot('medicineFront', 'shop') },
      { at: '10:00', label: 'making house calls', doing: patrol(['door:nagayaA', 'door:nagayaC', 'door:inn', 'door:samuraiIori', 'door:fishhut2'], undefined, 'stand', 12) },
      { at: '13:00', label: 'selling medicine', doing: spot('medicineFront', 'shop') },
      { at: '16:00', label: 'gathering herbs at the shrine woods', doing: spot('shrineFront', 'tend') },
      home('18:30'),
      asleep('22:30'),
    ],
    talk: [
      'Eat less salt, drink less sake, walk more. Nobody listens. That’s why there are doctors.',
      'Half my patients can pay. The other half live in tents by the moat. Guess which half I see more of.',
      'Turtles live ten thousand years. Whatever you’re doing, keep doing it.',
      'Danjūrō predicts doom; I treat it. We have an arrangement.',
    ],
    turtle: ['Hold still. …Shell: excellent. Eyes: sleepy. Diagnosis: turtle.'],
    shell: ['Retracted. Classic stress response. Prescription: tea.'],
    barks: { shop: ['Ginseng! Ginger! A jar of "do not"!', 'Bellyache? Headache? Heartache? Different jars.'], stand: ['Open up. Say "ah".'] },
  },
  {
    id: 'tetsuzo',
    name: 'Tetsuzō',
    title: 'blacksmith',
    home: 'door:smithy',
    color: '#4a4a4a',
    speed: 28,
    look: { hair: 'short', hat: 'hachimaki', robe: '#3d3449', robeShade: '#2a2233', sash: '#8a5a3a', legs: '#3d3449', collar: '#3d3449', extras: ['apron'] },
    schedule: [
      asleep(),
      { at: '06:00', label: 'hammering at the forge', doing: spot('anvil', 'hammer') },
      { at: '12:00', label: 'lunch at the inn', doing: spot('innFront', 'sit') },
      { at: '13:00', label: 'hammering at the forge', doing: spot('anvil', 'hammer') },
      { at: '18:30', label: 'soaking at the bathhouse', doing: spot('bathFront') },
      home('20:00'),
      asleep('21:00'),
    ],
    talk: [
      'Kitchen knives, farm hoes, the odd sword. Swords are boring. Hoes feed people.',
      'Spearheads. The castle wants two hundred spearheads by autumn. Nobody’s said what for. Nobody ever does.',
      'Samurai think the sword is the soul. The sword is iron I hit with a hammer. I’m the soul.',
      'Stand back, turtle. Sparks. You’re flammable. Probably.',
    ],
    turtle: ['A turtle at the forge! Want a little iron helmet? …You already have one, don’t you.'],
    shell: ['Good shell. I couldn’t forge better. Don’t tell the samurai.'],
    barks: { hammer: ['CLANG!', 'CLANG! CLANG!', 'Hot iron waits for no one.'] },
  },
  {
    id: 'goro',
    name: 'Gorō',
    title: 'carpenter',
    home: 'door:carpenter',
    color: '#a87a4a',
    speed: 30,
    look: { hair: 'short', hat: 'hachimaki', robe: '#8f6038', robeShade: '#6a4426', sash: '#2f3f73', legs: '#2f3f73', collar: '#2f3f73', extras: ['happi'] },
    schedule: [
      asleep(),
      { at: '06:30', label: 'fixing things around town', doing: work('carpentry', 'hammer') },
      { at: '11:00', label: 'repairing the shipwright’s ramp', doing: work('shipwrightYard', 'hammer') },
      { at: '13:00', label: 'fixing the temple stairs', doing: work('stairs', 'hammer') },
      { at: '17:00', label: 'drinking at the tavern', doing: spot('tavernFront', 'sit') },
      home('20:00'),
      asleep('21:00'),
    ],
    talk: [
      'A Japanese house is held together with no nails. Just joints, skill, and prayer. Mostly prayer.',
      'The temple stairs have 1,082 steps. I’ve fixed 1,081. Number 541 hates me.',
      'If anything in this town creaks, I’ve fixed it. If it still creaks, it’s Rihei’s.',
    ],
    turtle: ['A turtle! A natural roof. I respect the craftsmanship.'],
    shell: ['Mm, sturdy. Who built you? Never mind.'],
    barks: { hammer: ['Tok tok tok.', 'Measure twice, cut once, swear three times.', 'There we go.'] },
  },
  {
    id: 'okane',
    name: 'Okane',
    title: 'umbrella maker',
    home: 'door:umbrella',
    color: '#d06a3a',
    speed: 26,
    look: { hair: 'bun', robe: '#a85a3a', robeShade: '#844428', sash: '#e0b13c', legs: '#3d3449', collar: '#f1e6cc' },
    schedule: [
      asleep(),
      { at: '07:00', label: 'oiling paper umbrellas', doing: spot('umbrellaFront', 'sit') },
      { at: '11:30', label: 'selling umbrellas in the square', doing: spot('fanStall', 'shop') },
      { at: '15:00', label: 'oiling paper umbrellas', doing: spot('umbrellaFront', 'sit') },
      home('18:00'),
      asleep('22:00'),
    ],
    talk: [
      'Rainy season is coming. Everyone laughs at umbrellas until the sky opens. Then I’m a genius.',
      'Bamboo ribs, mulberry paper, persimmon oil. And patience. Lots of patience.',
      'You’re a turtle. You ARE an umbrella. I’m a little jealous.',
    ],
    turtle: ['A built-in umbrella! Competition!'],
    shell: ['If that stone had a handle it would be my best umbrella.'],
    barks: { sit: ['Rib, paper, oil…', 'Hmm-hm-hmm.'], shop: ['Umbrellas! The rain is coming!', 'Fans and umbrellas! Weather for everyone!'] },
  },
  {
    id: 'seiroku',
    name: 'Seiroku',
    title: 'night fire watchman',
    home: 'door:nagayaB',
    color: '#e0b13c',
    speed: 26,
    look: { hair: 'grayBun', hat: 'kasa', robe: '#3a3a4a', robeShade: '#2a2a36', sash: '#e0b13c', legs: '#3a3a4a', collar: '#e0b13c' },
    schedule: [
      { at: '00:00', label: 'fire watch round the streets', doing: patrol(['mainStreetW', 'samuraiLane', 'riceFront', 'castleGateGuard', 'mainStreetE', 'southStreetE', 'wallLaneE', 'wallLaneW', 'southStreetW'], undefined, 'call', 2) },
      asleep('04:30'),
      home('13:00', 'breakfast (at one in the afternoon)'),
      { at: '15:00', label: 'watching from the fire tower', doing: spot('watchtowerFoot', 'stand') },
      { at: '18:00', label: 'supper at the teahouse', doing: spot('teaBench4', 'sit') },
      { at: '19:30', label: 'fire watch round the streets', doing: patrol(['mainStreetW', 'samuraiLane', 'riceFront', 'castleGateGuard', 'mainStreetE', 'southStreetE', 'wallLaneE', 'wallLaneW', 'southStreetW'], undefined, 'call', 2), say: 'Hi no yōjin! Beware of fire!' },
    ],
    talk: [
      'Hi no yōjin! Beware of fire! …Sorry. Habit. I say it in my sleep. My wife left.',
      'I watched that house on Brewery Street burn. Rang the bell till my arms gave out. Nobody came with buckets. Funny, that.',
      'Wooden town, paper walls, everyone cooking over charcoal. Somebody has to walk around shouting.',
      'Clack clack! These clappers have woken every baby in Kumoi. I am not popular. I am necessary.',
    ],
    turtle: ['Hi no yōjin! …Oh, it’s you. Turtles don’t burn easily, do they? Good. One less worry.'],
    shell: ['A stone. Stones don’t burn. I like stones.'],
    barks: { call: ['Hi no yōjin! *clack clack*', 'Beware of fire! *clack*', 'Mind your charcoal! *clack clack*'], walk: ['*clack clack*'] },
  },
  {
    id: 'tokubei',
    name: 'Old Tokubei',
    title: 'storyteller',
    home: 'door:nagayaC',
    color: '#c4bdb0',
    speed: 20,
    look: { hair: 'grayBun', robe: '#6a6a5a', robeShade: '#4e4e42', sash: '#3d3449', legs: '#3d3449', collar: '#c9c1b0', extras: ['beard'] },
    schedule: [
      asleep(),
      home('07:00', 'remembering things'),
      { at: '09:30', label: 'telling stories under the camphor', doing: spot('camphor', 'sit') },
      { at: '12:00', label: 'napping on a bench', doing: spot('squareBench2', 'nap') },
      { at: '14:00', label: 'telling stories under the camphor', doing: spot('camphor', 'sit') },
      { at: '18:00', label: 'telling stories at the tavern', doing: spot('tavernFront', 'sit') },
      home('21:00'),
      asleep('21:30'),
    ],
    talk: [
      'When I was young, this town was three huts and a very angry goose. Then the castle came. The goose stayed angry.',
      'Shall I tell you about the kappa in the moat? It eats ducks, cucumbers and anyone who forgets to bow. Bow to it, turtle. Politeness costs nothing. Livers cost a lot.',
      'Did I tell you about the giant carp? Sanpei says it was his. It was MY carp. Forty years ago.',
      'The hermit on the island? I remember him when he was old. He was already old. He’s always been old.',
      'Long ago a turtle saved a fisherman and took him to the Dragon Palace under the sea. Was that you? You have the face.',
    ],
    turtle: ['A turtle! Like Urashima Tarō’s! Take me to the Dragon Palace! …No? Fine.'],
    shell: ['This reminds me of a story about a stone… no it doesn’t. I’m old.'],
    barks: { sit: ['Long, long ago…', '…and THAT’s why you never trust a goose.', 'Where was I?'], nap: ['Zzz… the goose… zzz…'] },
  },
  {
    id: 'hachi',
    name: 'Hachi',
    title: 'town urchin',
    home: 'door:houseHachi',
    color: '#d0a050',
    speed: 46,
    look: { kid: true, hair: 'kidBoy', robe: '#8a7a5a', robeShade: '#6a5a40', sash: '#c0262f', legs: '#f2c9a0' },
    schedule: [
      asleep(),
      { at: '06:00', label: '"helping" at the fish market', doing: spot('catFish', 'play') },
      { at: '08:00', label: 'playing with Taro and Kiku', doing: wander('square', 'play') },
      { at: '10:30', label: 'chasing seagulls', doing: wander('quay', 'play') },
      home('12:00', 'lunch'),
      { at: '13:00', label: 'climbing on the walls (forbidden)', doing: wander('samuraiLane', 'play') },
      { at: '15:00', label: 'racing up the temple stairs', doing: wander('stairs', 'play') },
      { at: '17:00', label: 'loitering by the tavern', doing: spot('tavernFront', 'play') },
      home('18:30', 'dinner'),
      asleep('20:30'),
    ],
    talk: [
      'I know every secret in Kumoi. The harbour master is hiding a boat. The castle has a cat. Matabei sleeps standing up.',
      'The new boy from Iga begs in the square. We threw mud at him. He threw it back better. Now he’s in our gang.',
      'Taro’s a farm kid. He thinks the moat is the sea. I let him.',
      'Wanna race? Up the temple stairs? …No, you’d lose. Wanna race anyway?',
      'Oshio at the fish market says if I steal one more fish she’ll sell ME. I don’t think I’d fetch much.',
    ],
    turtle: ['Whoa, a turtle! Can you swim to the island? Take me! The old man there has a pink house!'],
    shell: ['I know you’re in there. I can see your tail.'],
    barks: { play: ['Gull! GULL!', 'Bet you can’t catch me!', 'I didn’t take the fish! …That fish.'] },
  },
]

